name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Sorry you are experiencing that issue. Mypro will be with you shortly. (Hopefully)"
        pr-message: "Thank you for contributing. Your work is greatly appreciated."
